# Generated by Django 5.1.2 on 2024-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1', models.JSONField(blank=True, default=dict)),
                ('step2', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
